/*
 * File Name --> Driver_WaitState.h
 * Author	 --> Ahmed Mohamed Abd-Elfattah
 * Version	 --> 1.0.0
 * Layer	 --> Configurations
 * Brief	 --> Configuration of wait status of microcontroller.
 * */

#ifndef STM32_DRIVERS_CONFIGURATIONS_DRIVER_WAITSTATE_H_
#define STM32_DRIVERS_CONFIGURATIONS_DRIVER_WAITSTATE_H_


#define	DRIVER_OPERATING_VOLTAGE_IN_MS		3300

#define DRIVER_WAIT_STATE_ADDRESS_REGISTER	0x40023c00


/*Specify voltage ranges*/
#define DRIVER_VOLTAGE_RANGE_0_IN_MS_FROM	2700
#define DRIVER_VOLTAGE_RANGE_0_IN_MS_TO		3600

#define DRIVER_VOLTAGE_RANGE_1_IN_MS_FROM	2400
#define DRIVER_VOLTAGE_RANGE_1_IN_MS_TO		2700

#define DRIVER_VOLTAGE_RANGE_2_IN_MS_FROM	2100
#define DRIVER_VOLTAGE_RANGE_2_IN_MS_TO		2400

#define DRIVER_VOLTAGE_RANGE_3_IN_MS_FROM	1800
#define DRIVER_VOLTAGE_RANGE_3_IN_MS_TO		2100

/*	Voltage range 0*/
#define	DRIVER_WAIT_STATE_0_V0_FROM		0
#define	DRIVER_WAIT_STATE_0_V0_TO		30

#define	DRIVER_WAIT_STATE_1_V0_FROM		30
#define	DRIVER_WAIT_STATE_1_V0_TO		60

#define	DRIVER_WAIT_STATE_2_V0_FROM		60
#define	DRIVER_WAIT_STATE_2_V0_TO		90

#define	DRIVER_WAIT_STATE_3_V0_FROM		90
#define	DRIVER_WAIT_STATE_3_V0_TO		120

#define	DRIVER_WAIT_STATE_4_V0_FROM		120
#define	DRIVER_WAIT_STATE_4_V0_TO		150

#define	DRIVER_WAIT_STATE_5_V0_FROM		150
#define	DRIVER_WAIT_STATE_5_V0_TO		180


/*	Voltage range 1*/
#define	DRIVER_WAIT_STATE_0_V1_FROM		0
#define	DRIVER_WAIT_STATE_0_V1_TO		24

#define	DRIVER_WAIT_STATE_1_V1_FROM		24
#define	DRIVER_WAIT_STATE_1_V1_TO		48

#define	DRIVER_WAIT_STATE_2_V1_FROM		48
#define	DRIVER_WAIT_STATE_2_V1_TO		72

#define	DRIVER_WAIT_STATE_3_V1_FROM		72
#define	DRIVER_WAIT_STATE_3_V1_TO		96

#define	DRIVER_WAIT_STATE_4_V1_FROM		96
#define	DRIVER_WAIT_STATE_4_V1_TO		120

#define	DRIVER_WAIT_STATE_5_V1_FROM		120
#define	DRIVER_WAIT_STATE_5_V1_TO		144

#define	DRIVER_WAIT_STATE_6_V1_FROM		144
#define	DRIVER_WAIT_STATE_6_V1_TO		168

#define	DRIVER_WAIT_STATE_7_V1_FROM		168
#define	DRIVER_WAIT_STATE_7_V1_TO		180

/*	Voltage range 2*/
#define	DRIVER_WAIT_STATE_0_V2_FROM		0
#define	DRIVER_WAIT_STATE_0_V2_TO		22

#define	DRIVER_WAIT_STATE_1_V2_FROM		22
#define	DRIVER_WAIT_STATE_1_V2_TO		44

#define	DRIVER_WAIT_STATE_2_V2_FROM		44
#define	DRIVER_WAIT_STATE_2_V2_TO		66

#define	DRIVER_WAIT_STATE_3_V2_FROM		66
#define	DRIVER_WAIT_STATE_3_V2_TO		88

#define	DRIVER_WAIT_STATE_4_V2_FROM		88
#define	DRIVER_WAIT_STATE_4_V2_TO		110

#define	DRIVER_WAIT_STATE_5_V2_FROM		110
#define	DRIVER_WAIT_STATE_5_V2_TO		132

#define	DRIVER_WAIT_STATE_6_V2_FROM		132
#define	DRIVER_WAIT_STATE_6_V2_TO		154

#define	DRIVER_WAIT_STATE_7_V2_FROM		154
#define	DRIVER_WAIT_STATE_7_V2_TO		176

#define	DRIVER_WAIT_STATE_8_V2_FROM		176
#define	DRIVER_WAIT_STATE_8_V2_TO		180

/*	Voltage range 3*/
#define	DRIVER_WAIT_STATE_0_V3_FROM		0
#define	DRIVER_WAIT_STATE_0_V3_TO		20

#define	DRIVER_WAIT_STATE_1_V3_FROM		20
#define	DRIVER_WAIT_STATE_1_V3_TO		40

#define	DRIVER_WAIT_STATE_2_V3_FROM		40
#define	DRIVER_WAIT_STATE_2_V3_TO		60

#define	DRIVER_WAIT_STATE_3_V3_FROM		60
#define	DRIVER_WAIT_STATE_3_V3_TO		80

#define	DRIVER_WAIT_STATE_4_V3_FROM		80
#define	DRIVER_WAIT_STATE_4_V3_TO		100

#define	DRIVER_WAIT_STATE_5_V3_FROM		100
#define	DRIVER_WAIT_STATE_5_V3_TO		120

#define	DRIVER_WAIT_STATE_6_V3_FROM		120
#define	DRIVER_WAIT_STATE_6_V3_TO		140

#define	DRIVER_WAIT_STATE_7_V3_FROM		140
#define	DRIVER_WAIT_STATE_7_V3_TO		160

#define	DRIVER_WAIT_STATE_8_V3_FROM		160
#define	DRIVER_WAIT_STATE_8_V3_TO		168

#endif /* STM32_DRIVERS_CONFIGURATIONS_DRIVER_WAITSTATE_H_ */
